title: Kyle Wright's Homepage
author: Kyle Wright
subtitle: Cybersecurity at Marist College

url: "https://wright2002.github.io"
baseurl: "/system-design-project-1"

# Left to give credit to theme author
footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/headshot.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about.html"
 - name: "Resume"
   link: "resume"
